name: snowflake_profile
version: 1.0.0
config-version: 2
profile: snowflake_profile
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  snowflake_profile:
    +materialized: view
