name: principal_project
version: 1.0.0
config-version: 2
profile: dbt_profile
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  principal_project:
    staging:
      +materialized: view
      +schema: staging
    modeled:
      +materialized: table
      +schema: modeled
    incremental:
      +materialized: table
      +schema: incremental
    intermediate:
      +materialized: table
      +schema: intermediate


