name: principal_project
version: 1.0.0
config-version: 2
profile: dbt_profile
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  principal_project:
    staging:
      +materialized: view
      +schema: staging
      cold_stage:
        +tags:
          - cold
    modeled:
      +materialized: table
      +schema: modeled
      cold_stage:
        +tags:
          - cold
    intermediate:
      +materialized: table
      +schema: intermediate
      cold_stage:
        +tags:
          - cold
    incremental:
      +materialized: table
      +schema: incremental
      +tags:
        - incremental
      cold_stage:
        +tags:
          - cold
    bi:
      +materialized: view
      +schema: bi
      cold_stage:
        +tags:
          - cold


