dbt_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_PROJECT
      schema: DEV
      threads: 4
    prod:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_PROJECT
      schema: PROD
      threads: 8