dbt_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: TRANSFORMER
      warehouse: DBT_WH
      database: ANALYTICS
      schema: DEV
      threads: 4
    prod:
      type: snowflake
      role: TRANSFORMER
      warehouse: DBT_WH
      database: ANALYTICS
      schema: PROD
      threads: 6